Enhancement/improve bcrypt
sismics/docs pull request #490
Opened 2020-12-31 10:48 UTC by Vec7or

#488 I added a environment variable to specify the bcrypt-work-factor. There are still two To Do's within the code-base because I do not know how you want me to handle the logging.

2021-01-03 20:01 UTC, jendib requested changes
I added a few comments if you can resolve this. Thanks.

2021-01-03 20:01 UTC, jendib commented on docs-core/src/main/java/com/sismics/docs/core/dao/UserDao.java
> +                    //ToDo: Log warning? (out of scope)
Log using slf4j logger (please see FileService.java for example) as "warning" level and fallback to default bcrypt work.

2021-01-03 20:01 UTC, jendib commented on docs-core/src/main/java/com/sismics/docs/core/dao/UserDao.java
> +                //ToDo: Log warning? (no number)
Same as above

2021-01-03 20:01 UTC, jendib commented on docs-core/src/main/java/com/sismics/docs/core/dao/UserDao.java
> +        System.out.println(bcryptWork);
Please remove

2021-01-04 18:26 UTC, Vec7or commented on docs-core/src/main/java/com/sismics/docs/core/dao/UserDao.java
> +        System.out.println(bcryptWork);
I must have overlooked that 😄.

2021-01-04 18:26 UTC, Vec7or commented
Adjusted the code according to the review.

2021-01-05 17:56 UTC, jendib approved these changes

2021-01-05 17:59 UTC, merged