Add missing french translations
sismics/docs pull request #694
Opened 2023-06-02 08:36 UTC by archiloque

2023-06-04 19:46 UTC, jendib requested changes

2023-06-04 19:46 UTC, jendib commented on docs-web/src/main/webapp/src/locale/fr.json
> +      "deleteImported": "Delete message from mailbox after import"
Encore un peu d'anglais ici :)

2023-06-05 07:00 UTC, archiloque commented on docs-web/src/main/webapp/src/locale/fr.json
> +      "deleteImported": "Delete message from mailbox after import"
Woups désolé, c'est corrigé !

2023-06-05 11:12 UTC, jendib requested changes
"les message**s**"

2023-06-05 13:55 UTC, archiloque commented
> "les message**s**"

J'ai hésité entre singulier et pluriel et au final j'ai mélangé les deux, c'est corrigé 😓

2023-06-05 14:02 UTC, merged